package com.example.myfilterproject;

import jakarta.websocket.server.ServerEndpoint;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.ServletComponentScan;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@ServletComponentScan(basePackages = "com.example.myfilterproject.filter")
public class MyFilterProjectApplication {

    public static void main(String[] args) {
        SpringApplication.run(MyFilterProjectApplication.class, args);
    }

}
