#spring.application.name=mybatisplus
#\u63A8\u8350\u7528application.yml
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML

  application:
    name: mybatisplus
  #\u8FDE\u63A5\u6570\u636E\u5E93
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: szyh2016
#logging:
#  level:
#    org.springframework.boot.autoconfigure: DEBUG
myapp:
  #\u6D4B\u8BD5\u8FD9\u4E2A\u6587\u4EF6\u751F\u6548\u6CA1 \u53EF\u5728java\u5185\u76F4\u63A5\u8FD9\u6837\u8BBF\u95EE @Value("${myapp.greeting}")
  greeting: 我是pro
server:
  #\u8BBE\u7F6E\u8BBF\u95EE\u7AEF\u53E3\u53F7
  port: 9009
  #\u5E94\u7528\u7684 contextpath
  servlet:
    context-path: /mybatisplus

#mybatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   #扫描包
  type-aliases-package: com.example.mybatisplus.pojo

# MyBatis-Plus \u914D\u7F6E
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  type-aliases-package: com.yourpackage.model
#  global-config:
#    db-config:
#      id-type: auto
#      table-prefix: t_
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致