package com.example.ormmysql;

import org.mybatis.spring.annotation.MapperScan;
import org.mybatis.spring.annotation.MapperScans;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan(value = {"com.example.ormmysql.dao"})
public class OrmMysqlApplication {

    public static void main(String[] args) {
        SpringApplication.run(OrmMysqlApplication.class, args);
    }

}
